\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={RESURAL (JcB)},
            pdftitle={Activité des SAMU : panorama 2014 de la région ALSACE},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{5}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Activité des SAMU : panorama 2014 de la région ALSACE}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{RESURAL (JcB)}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{28/01/2015}



\begin{document}

\maketitle


{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Analyse SAMU}\label{analyse-samu}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(knitr)}
\KeywordTok{library}\NormalTok{(}\StringTok{"xts"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: zoo
## 
## Attaching package: 'zoo'
## 
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"zoo"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"lubridate"}\NormalTok{)}

\CommentTok{# supprimer la notation scientifique et ajouter un séparateur de milliers}
\KeywordTok{options}\NormalTok{(}\DataTypeTok{scipen =} \DecValTok{6}\NormalTok{, }\DataTypeTok{digits =} \DecValTok{2}\NormalTok{)}
\NormalTok{knit_hooks$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{inline =} \NormalTok{function(x) \{}
  \KeywordTok{prettyNum}\NormalTok{(x, }\DataTypeTok{big.mark=}\StringTok{" "}\NormalTok{)}
\NormalTok{\})}

\KeywordTok{load}\NormalTok{(}\StringTok{"samu_archive.Rda"}\NormalTok{)}

\KeywordTok{names}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "date"        "service"     "affaires"    "primaires"   "secondaires"
##  [6] "néonat"      "TIIH"        "ASSU"        "VSAV"        "conseils"   
## [11] "Medecins"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{min}\NormalTok{(d$date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2006-01-01"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{max}\NormalTok{(d$date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2015-12-01"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop67 <-}\StringTok{ }\DecValTok{1095905}
\NormalTok{pop68 <-}\StringTok{ }\DecValTok{749782}
\NormalTok{pop.als}\FloatTok{.2010}\NormalTok{.municipale<-}\DecValTok{1095905} \NormalTok{+}\StringTok{ }\DecValTok{749782}

\CommentTok{# on met à NA les enregistrements où le nombre d'affaires < 10}


\CommentTok{# année courante et nb de jours}
\NormalTok{an_c <-}\StringTok{ }\DecValTok{2014}

\NormalTok{d <-}\StringTok{ }\NormalTok{d[}\KeywordTok{year}\NormalTok{(d$date) <}\StringTok{ }\NormalTok{an_c}\DecValTok{+1}\NormalTok{,]}

\NormalTok{j1 <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(an_c,}\StringTok{"-01-01"}\NormalTok{))}
\NormalTok{j2 <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(an_c,}\StringTok{"-12-31"}\NormalTok{))}
\NormalTok{n <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(j2-j1) +}\StringTok{ }\DecValTok{1}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 365
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "date"        "service"     "affaires"    "primaires"   "secondaires"
##  [6] "néonat"      "TIIH"        "ASSU"        "VSAV"        "conseils"   
## [11] "Medecins"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    6301 obs. of  11 variables:
##  $ date       : Date, format: "2006-12-31" "2006-12-30" ...
##  $ service    : Factor w/ 2 levels "SAMU 67","SAMU 68": 1 1 1 1 1 1 1 1 1 1 ...
##  $ affaires   : num  1450 1202 753 744 851 ...
##  $ primaires  : num  34 36 20 37 41 36 28 40 48 48 ...
##  $ secondaires: num  5 8 12 8 10 2 6 3 7 11 ...
##  $ néonat     : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ TIIH       : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ ASSU       : num  124 110 80 75 123 108 115 96 100 101 ...
##  $ VSAV       : num  18 6 13 13 12 11 12 12 18 15 ...
##  $ conseils   : num  150 92 50 84 64 145 185 145 117 47 ...
##  $ Medecins   : num  329 209 76 62 61 371 337 354 151 51 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       date               service        affaires      primaires 
##  Min.   :2006-01-01   SAMU 67:3284   Min.   :   0   Min.   : 0  
##  1st Qu.:2008-03-08   SAMU 68:3017   1st Qu.: 399   1st Qu.:19  
##  Median :2010-05-04                  Median : 583   Median :28  
##  Mean   :2010-06-13                  Mean   : 613   Mean   :29  
##  3rd Qu.:2012-11-07                  3rd Qu.: 741   3rd Qu.:37  
##  Max.   :2014-12-31                  Max.   :2194   Max.   :89  
##   secondaires     néonat         TIIH        ASSU          VSAV    
##  Min.   : 0   Min.   :0.0   Min.   :0   Min.   :  0   Min.   :  0  
##  1st Qu.: 4   1st Qu.:0.0   1st Qu.:0   1st Qu.: 27   1st Qu.: 20  
##  Median : 6   Median :0.0   Median :0   Median : 83   Median : 36  
##  Mean   : 7   Mean   :0.7   Mean   :0   Mean   : 71   Mean   : 44  
##  3rd Qu.: 9   3rd Qu.:1.0   3rd Qu.:0   3rd Qu.:102   3rd Qu.: 69  
##  Max.   :34   Max.   :8.0   Max.   :7   Max.   :160   Max.   :126  
##     conseils      Medecins  
##  Min.   :  0   Min.   :  0  
##  1st Qu.: 60   1st Qu.: 41  
##  Median :105   Median : 55  
##  Mean   :118   Mean   : 87  
##  3rd Qu.:145   3rd Qu.:115  
##  Max.   :599   Max.   :593
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nombre d'année dans la base:}
\KeywordTok{table}\NormalTok{(}\KeywordTok{year}\NormalTok{(d$date))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 2006 2007 2008 2009 2010 2011 2012 2013 2014 
##  714  726  729  735  726  646  559  731  735
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nombre d'affaires par an:}
\NormalTok{taf <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$affaires, }\KeywordTok{year}\NormalTok{(d$date), sum)}

\CommentTok{# nombre moyen d'affaires}
\NormalTok{maf <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$affaires, }\KeywordTok{year}\NormalTok{(d$date), mean)}

\CommentTok{# écart-type nombre d'affaires}
\NormalTok{saf <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$affaires, }\KeywordTok{year}\NormalTok{(d$date), sd)}

\CommentTok{# primaires}
\NormalTok{tpr <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$primaires, }\KeywordTok{year}\NormalTok{(d$date), sum)}
\CommentTok{# secondaires}
\NormalTok{tse <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$secondaires, }\KeywordTok{year}\NormalTok{(d$date), sum)}
\CommentTok{# SMUR}
\NormalTok{tsm <-}\StringTok{ }\NormalTok{tpr+tse}
\CommentTok{# ASSU}
\NormalTok{tas <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$ASSU, }\KeywordTok{year}\NormalTok{(d$date), sum)}
\CommentTok{# VSAV}
\NormalTok{tvs <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$VSAV, }\KeywordTok{year}\NormalTok{(d$date), sum)}
\CommentTok{# Conseils}
\NormalTok{tco <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$conseils, }\KeywordTok{year}\NormalTok{(d$date), sum)}
\CommentTok{# visites}
\NormalTok{tme <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$Medecins, }\KeywordTok{year}\NormalTok{(d$date), sum)}

\NormalTok{t <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(taf,tco,tsm,tas,tvs,tme)}
\KeywordTok{rownames}\NormalTok{(t) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Affaires"}\NormalTok{,}\StringTok{"Conseils"}\NormalTok{,}\StringTok{"SMUR"}\NormalTok{,}\StringTok{"ASSU"}\NormalTok{,}\StringTok{"VSAV"}\NormalTok{,}\StringTok{"Médecins"}\NormalTok{)}
\NormalTok{t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            2006   2007   2008   2009   2010   2011   2012   2013   2014
## Affaires 394904 431340 432576 446044 429529 412890 414947 417157 480303
## Conseils  86124  79961  81572  94640  84969  77585  58646  87921  91412
## SMUR      25547  25625  25766  26545  25015  23214  22724  24494  24784
## ASSU      57243  63190  61788  40807  46350  44360  42366  42167  46031
## VSAV      22779  23379  29168  33984  33238  29169  25213  40281  41475
## Médecins  55588  67981  69448  74293  65509  59062  48704  53820  54723
\end{verbatim}

\section{Bilan régional}\label{bilan-regional}

\begin{verbatim}
## [1] "Année 2014"
\end{verbatim}

\begin{verbatim}
##    affaires   primaires secondaires      néonat        TIIH        ASSU 
##      480303       19714        5070         537           0       46031 
##        VSAV    conseils    Medecins 
##       41475       91412       54723
\end{verbatim}

\begin{verbatim}
## [1] "Par jour:"
\end{verbatim}

\begin{verbatim}
##    affaires   primaires secondaires      néonat        TIIH        ASSU 
##      1315.9        54.0        13.9         1.5         0.0       126.1 
##        VSAV    conseils    Medecins 
##       113.6       250.4       149.9
\end{verbatim}

\section{Records}\label{records}

\subsection{maximaux}\label{maximaux}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$affaires==}\KeywordTok{max}\NormalTok{(d$affaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 2176 2009-12-26 SAMU 67     2194        54           5      0    0  137
##      VSAV conseils Medecins
## 2176   34      200      581
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$primaires==}\KeywordTok{max}\NormalTok{(d$primaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 2442 2009-04-04 SAMU 67     1168        89           5      0    0  131
##      VSAV conseils Medecins
## 2442   19      105      194
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$secondaires==}\KeywordTok{max}\NormalTok{(d$secondaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 1715 2008-04-02 SAMU 67      740        36          34      1    0  103
##      VSAV conseils Medecins
## 1715   14       39       68
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$ASSU==}\KeywordTok{max}\NormalTok{(d$ASSU, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 1807 2008-01-01 SAMU 67     1667        46           5      1    0  160
##      VSAV conseils Medecins
## 1807   26      215      308
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$VSAV==}\KeywordTok{max}\NormalTok{(d$VSAV, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 5963 2014-06-12 SAMU 68      558        25           5      0    0   30
##      VSAV conseils Medecins
## 5963  126      133       25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$conseils==}\KeywordTok{max}\NormalTok{(d$conseils, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           date service affaires primaires secondaires néonat TIIH ASSU
## 363 2006-12-26 SAMU 68      888        16           7      1    0   73
##     VSAV conseils Medecins
## 363   38      599      403
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$Medecins==}\KeywordTok{max}\NormalTok{(d$Medecins, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 1447 2008-12-26 SAMU 67     1911        51           5      1    0  126
##      VSAV conseils Medecins
## 1447   38      246      593
\end{verbatim}

\subsection{minimaux}\label{minimaux}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$affaires==}\KeywordTok{min}\NormalTok{(d$affaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 483  2006-08-29 SAMU 68        0         0           0      0    0    0
## 524  2006-07-19 SAMU 68        0         0           0      0    0    0
## 1368 2007-03-15 SAMU 68        0         0           0      0    0    0
##      VSAV conseils Medecins
## 483     0        0        0
## 524     0        0        0
## 1368    0        0        0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$primaires==}\KeywordTok{min}\NormalTok{(d$primaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 483  2006-08-29 SAMU 68        0         0           0      0    0    0
## 524  2006-07-19 SAMU 68        0         0           0      0    0    0
## 1368 2007-03-15 SAMU 68        0         0           0      0    0    0
##      VSAV conseils Medecins
## 483     0        0        0
## 524     0        0        0
## 1368    0        0        0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d[d$secondaires==}\KeywordTok{min}\NormalTok{(d$secondaires, }\DataTypeTok{na.rm=}\NormalTok{T) &}\StringTok{ }\NormalTok{!}\KeywordTok{is.na}\NormalTok{(d$date),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 77   2006-10-17 SAMU 67      608        38           0      0    7   86
## 377  2006-12-12 SAMU 68      307        19           0      0    0   63
## 380  2006-12-09 SAMU 68      430        17           0      0    0   72
## 387  2006-12-02 SAMU 68      438        27           0      0    0   67
## 483  2006-08-29 SAMU 68        0         0           0      0    0    0
## 524  2006-07-19 SAMU 68        0         0           0      0    0    0
## 578  2006-05-27 SAMU 68      492        33           0      0    0   93
## 591  2006-05-14 SAMU 68      485        26           0      0    0   58
## 607  2006-04-27 SAMU 68      303        16           0      0    0   68
## 654  2006-03-05 SAMU 68      621        34           0      0    0   87
## 795  2007-10-13 SAMU 67      840        37           0      1    0  101
## 1123 2007-11-18 SAMU 68      480        17           0      0    0   76
## 1262 2007-07-02 SAMU 68      336        26           0      0    0   77
## 1335 2007-04-20 SAMU 68      306        17           0      0    0   53
## 1368 2007-03-15 SAMU 68        0         0           0      0    0    0
## 1460 2008-12-13 SAMU 67      848        27           0      1    0  115
## 1874 2008-10-25 SAMU 68      429        27           0      0    0   76
## 1946 2008-08-14 SAMU 68      333        18           0      0    0   62
## 1952 2008-08-08 SAMU 68      292        11           0      0    0   54
## 1990 2008-06-30 SAMU 68      372        29           0      0    0   70
## 2086 2008-03-25 SAMU 68      366        19           0      0    0   60
## 2288 2009-09-05 SAMU 67      713        40           0      0    0  101
## 2607 2009-10-25 SAMU 68      490        20           0      0    0    0
## 2863 2009-02-15 SAMU 68      646        18           0      0    0    0
## 2872 2009-02-06 SAMU 68      357        15           0      0    0    0
## 3135 2010-05-16 SAMU 67     1277        32           0      0    0   94
## 3593 2010-02-08 SAMU 68      358        16           0      0    0   16
## 3667 2011-11-26 SAMU 67      833        30           0      0    0   83
## 3722 2011-10-02 SAMU 67     1297        30           0      0    0  111
## 3975 2011-01-22 SAMU 67      972        28           0      0    0  100
## 4058 2011-08-11 SAMU 68      333        17           0      0    0   17
## 4287 2012-12-22 SAMU 67     1339        59           0      0    0  109
## 4613 2012-01-31 SAMU 67      733        41           0      0    0  106
## 4787 2012-08-09 SAMU 68      437        15           0      0    0   15
## 4882 2013-06-16 SAMU 67      574        46           0      0    0   90
## 5157 2013-04-14 SAMU 68      750        23           0      0    0   23
## 5388 2013-10-27 SAMU 67      459        22           0      0    0   76
## 5418 2013-10-28 SAMU 68      432        17           0      0    0   17
## 5714 2014-05-18 SAMU 67      952        36           0      0    0   98
## 5757 2014-04-05 SAMU 67      809        36           0      0    0  107
## 5764 2014-03-29 SAMU 67      981        34           0      1    0  121
##      VSAV conseils Medecins
## 77     11       47       51
## 377    52      102       39
## 380    53      190      126
## 387    58      187      145
## 483     0        0        0
## 524     0        0        0
## 578    66      308      123
## 591    57      398      127
## 607    41      135       38
## 654    59      422      153
## 795    17      100      129
## 1123   33      208      165
## 1262   63      102       45
## 1335   48       87       44
## 1368    0        0        0
## 1460   19      106      194
## 1874   66      170      109
## 1946   62      133       36
## 1952   45      120       34
## 1990   86      132       48
## 2086   59      124       41
## 2288   18       97      141
## 2607   83      199      172
## 2863   94      246      228
## 2872   72      131       38
## 3135   29      177      214
## 3593   64      145       51
## 3667   21      131      140
## 3722   27      175      257
## 3975   23      121      170
## 4058   65      111       38
## 4287   34      129      235
## 4613   20       59       50
## 4787  102      106       34
## 4882   44      141      179
## 5157  109      190      109
## 5388   15       92      199
## 5418   72      133       27
## 5714   18      120      168
## 5757   34       75      126
## 5764   31      120      132
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# d[d$ASSU==min(d$ASSU, na.rm=T) & !is.na(d$date),]}
\CommentTok{# d[d$VSAV==min(d$VSAV, na.rm=T) & !is.na(d$date),]}
\CommentTok{# d[d$conseils==min(d$conseils, na.rm=T) & !is.na(d$date),]}
\CommentTok{# d[d$Medecins==min(d$Medecins, na.rm=T) & !is.na(d$date),]}
\end{Highlighting}
\end{Shaded}

\section{SAMU 67}\label{samu-67}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s67 <-}\StringTok{ }\NormalTok{d[d$service ==}\StringTok{ "SAMU 67"}\NormalTok{,]}
\CommentTok{# supprime les lignes dupliquées:}
\NormalTok{s67 <-}\StringTok{ }\NormalTok{s67[!}\KeywordTok{duplicated}\NormalTok{(s67$date),]}
\CommentTok{# nombre d'affaires}
\NormalTok{n_67_affaires <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(s67$affaires)}

\NormalTok{s_s67 <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(s67)}

\NormalTok{xts_s67 <-}\StringTok{ }\KeywordTok{as.xts}\NormalTok{(s67, }\DataTypeTok{order.by =} \NormalTok{s67$date)}

\NormalTok{a <-}\StringTok{ }\KeywordTok{zoo}\NormalTok{(s67$affaires, s67$date)}
\KeywordTok{plot}\NormalTok{(a, }\DataTypeTok{col=}\StringTok{"palegreen"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"Activité du SAMU 67"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu67-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b <-}\StringTok{ }\KeywordTok{zoo}\NormalTok{(s67$conseils, s67$date)}
\KeywordTok{plot}\NormalTok{(b, }\DataTypeTok{col=}\StringTok{"palegreen"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"Activité du SAMU 67"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre de conseils"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu67-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s67$affaires,}\KeywordTok{year}\NormalTok{(s67$date),sum)}
\CommentTok{# activité en nombre d'affaires}
\NormalTok{a}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   2006   2007   2008   2009   2010   2011   2012   2013   2014 
## 258065 291264 287750 286857 279600 290592 323647 223414 299899
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# moyenne des dossiers:}
\NormalTok{a <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s67$affaires,}\KeywordTok{year}\NormalTok{(s67$date),mean)}

\NormalTok{b <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s67$affaires,}\KeywordTok{year}\NormalTok{(s67$date),sd)}
\NormalTok{c <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(a,b)}
\KeywordTok{rownames}\NormalTok{(c) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"moy"}\NormalTok{,}\StringTok{"e-type"}\NormalTok{)}
\NormalTok{c}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        2006 2007 2008 2009 2010 2011 2012 2013 2014
## moy     725  798  786  786  766  796  884  612  822
## e-type  195  237  236  240  220  207  207  321  180
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(a, }\DataTypeTok{type=}\StringTok{"l"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nb.moyen d'affaires/j"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{""}\NormalTok{,}\DataTypeTok{main=}\StringTok{"SAMU 67 - Evolution du nombre des affaires"}\NormalTok{, }\DataTypeTok{axes =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{)}
\KeywordTok{axis}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{:}\DecValTok{9}\NormalTok{,}\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\DecValTok{2006}\NormalTok{:}\DecValTok{2014}\NormalTok{))}
\KeywordTok{axis}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu67-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# box plot. On détermine la journée la plus active en triant les enregistrements par nb affaires décroissant. ord[1] correspond à la ligne où le nb d'affaires est le plus élevé. Il s'agxit de 2006, ce qui correspond à la colonne n°4. On marque la date en face du repère.}

\CommentTok{# moyenne annuelle}
\NormalTok{moy67 <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s67$affaires,}\KeywordTok{year}\NormalTok{(s67$date),mean)}

\KeywordTok{boxplot}\NormalTok{(s67$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(s67$date), }\DataTypeTok{main=}\StringTok{"Activité du SAMU 67"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{)}
\NormalTok{for(i in }\DecValTok{1}\NormalTok{:}\DecValTok{9}\NormalTok{)\{}\KeywordTok{points}\NormalTok{(i,moy67[i],}\DataTypeTok{col=}\StringTok{"red"}\NormalTok{)\}}

\NormalTok{ord <-}\StringTok{ }\KeywordTok{order}\NormalTok{(s67$affaires,}\DataTypeTok{decreasing=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{s67[ord[}\DecValTok{1}\NormalTok{],]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 2176 2009-12-26 SAMU 67     2194        54           5      0    0  137
##      VSAV conseils Medecins
## 2176   34      200      581
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s67$date[ord[}\DecValTok{1}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2009-12-26"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{text}\NormalTok{(}\DecValTok{4}\NormalTok{, s67$affaires[ord[}\DecValTok{1}\NormalTok{]], s67$date[ord[}\DecValTok{1}\NormalTok{]],}\DataTypeTok{cex=}\NormalTok{.}\DecValTok{6}\NormalTok{,}\DataTypeTok{pos=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu67-4.pdf} \#\#\#\# chiffres
résumés sur la période 2006 - 2 014:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  nombre d'affaires: 2 541 088
\item
  moyenne des affaires/j: Mean : 775\\
\item
  médiane des affaires/j: Median : 721\\
\item
  nombre maximal d' affaires/j: Max. :2194\\
\item
  nombre minimal d' affaires/j: Min. : 78
\end{itemize}

\subsection{bilan de l'année 2 014}\label{bilan-de-lannee-2-014}

En 2013, une erreur informatique a entraîné une erreur dans le report de
l'activité du SAMU67 du 24 avril 2013 au 1er novembre 2013, soit un peu
plus de 6 mois:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  \textbf{ac67} correspond à l'ensemble de l'année 2013
\item
  \textbf{ac67c} correspond aux mois 1-4 et 11-12 de 2013
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ac67 <-}\StringTok{ }\NormalTok{s67[}\KeywordTok{year}\NormalTok{(s67$date) ==}\StringTok{ }\NormalTok{an_c,]}
\CommentTok{# nombre de jours renseignés}
\NormalTok{x <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{max}\NormalTok{(ac67$date, }\DataTypeTok{na.rm=}\NormalTok{T) -}\StringTok{ }\KeywordTok{min}\NormalTok{(ac67$date, }\DataTypeTok{na.rm=}\NormalTok{T))}
\KeywordTok{round}\NormalTok{(x *}\StringTok{ }\DecValTok{100} \NormalTok{/}\StringTok{ }\NormalTok{n, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#nb affaires:}
\NormalTok{n_ac67_af <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$affaires, }\DataTypeTok{na.rm=}\NormalTok{T)}
\NormalTok{sac67_af <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$affaires)}
\NormalTok{sac67_af}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     480     688     784     822     929    1540
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nb primaires}
\NormalTok{n_ac67_pr <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$primaires)}
\NormalTok{sac67_pr <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$primaires)}
\NormalTok{sac67_pr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      17      31      36      36      41      60
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nb secondaires}
\NormalTok{n_ac67_tr <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$secondaires)}
\NormalTok{sac67_tr <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$secondaires)}
\NormalTok{sac67_tr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0     5.0     7.0     7.7    10.0    18.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nb de SMUR (primaires + secondaires)}
\NormalTok{p <-}\StringTok{ }\NormalTok{ac67$primaires}
\NormalTok{t <-}\StringTok{ }\NormalTok{ac67$secondaires}
\NormalTok{s <-}\StringTok{ }\NormalTok{p +}\StringTok{ }\NormalTok{t}
\NormalTok{n_smur67 <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(s, }\DataTypeTok{na.rm=}\NormalTok{T)}
\NormalTok{n_smur67}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15877
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s_smur67 <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(s)}
\CommentTok{# nb de mise en oeuvre d'ASSU}
\NormalTok{n_ac67_as <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$ASSU)}
\NormalTok{sac67_as <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$ASSU)}
\NormalTok{sac67_as}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      74      93     101     101     108     138
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nb de mise en oeuvre de VSAV à la demande du SAMU}
\NormalTok{n_ac67_vs <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$VSAV)}
\NormalTok{sac67_vs <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$VSAV)}
\NormalTok{sac67_vs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      11      25      29      30      34      50
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nombre de conseils médicaux}
\NormalTok{n_ac67_cs <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$conseils)}
\NormalTok{sac67_cs <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$conseils)}
\NormalTok{sac67_cs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      34      63      75      87     107     247
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# nombre de Médecins déclenchés par le SAMU}
\NormalTok{n_ac67_md <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(ac67$Medecins)}
\NormalTok{sac67_md <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ac67$Medecins)}
\NormalTok{sac67_md}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      22      45      55      93     129     386
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# comparaison avec l'année précédante:}
\NormalTok{ap67 <-}\StringTok{ }\NormalTok{s67[}\KeywordTok{year}\NormalTok{(s67$date) ==}\StringTok{ }\NormalTok{an_c}\DecValTok{-1}\NormalTok{,]}
\NormalTok{sap67 <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(ap67)}
\NormalTok{sap67}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       date               service       affaires      primaires 
##  Min.   :2013-01-01   SAMU 67:365   Min.   : 234   Min.   :16  
##  1st Qu.:2013-04-02   SAMU 68:  0   1st Qu.: 317   1st Qu.:31  
##  Median :2013-07-02                 Median : 492   Median :36  
##  Mean   :2013-07-02                 Mean   : 612   Mean   :37  
##  3rd Qu.:2013-10-01                 3rd Qu.: 841   3rd Qu.:41  
##  Max.   :2013-12-31                 Max.   :1446   Max.   :60  
##   secondaires       néonat         TIIH        ASSU          VSAV   
##  Min.   : 0.0   Min.   :0.0   Min.   :0   Min.   : 57   Min.   :12  
##  1st Qu.: 5.0   1st Qu.:0.0   1st Qu.:0   1st Qu.: 81   1st Qu.:24  
##  Median : 8.0   Median :1.0   Median :0   Median : 91   Median :28  
##  Mean   : 7.6   Mean   :1.4   Mean   :0   Mean   : 93   Mean   :29  
##  3rd Qu.:10.0   3rd Qu.:2.0   3rd Qu.:0   3rd Qu.:103   3rd Qu.:33  
##  Max.   :19.0   Max.   :8.0   Max.   :0   Max.   :153   Max.   :67  
##     conseils      Medecins  
##  Min.   : 26   Min.   : 21  
##  1st Qu.: 51   1st Qu.: 42  
##  Median : 67   Median : 53  
##  Mean   : 78   Mean   : 91  
##  3rd Qu.: 94   3rd Qu.:122  
##  Max.   :252   Max.   :356
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# analyse en ne trenant compte que des mois pleins (mois 1-4 et 11-12)}
\NormalTok{ac67c <-}\StringTok{ }\NormalTok{ac67[ac67$date <}\StringTok{ "2013-04-24"} \NormalTok{|}\StringTok{ }\NormalTok{ac67$date >}\StringTok{ "2013-11-01"}\NormalTok{,]}
\KeywordTok{summary}\NormalTok{(ac67c)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       date               service       affaires      primaires 
##  Min.   :2014-01-01   SAMU 67:365   Min.   : 480   Min.   :17  
##  1st Qu.:2014-04-02   SAMU 68:  0   1st Qu.: 688   1st Qu.:31  
##  Median :2014-07-02                 Median : 784   Median :36  
##  Mean   :2014-07-02                 Mean   : 822   Mean   :36  
##  3rd Qu.:2014-10-01                 3rd Qu.: 929   3rd Qu.:41  
##  Max.   :2014-12-31                 Max.   :1537   Max.   :60  
##   secondaires       néonat         TIIH        ASSU          VSAV   
##  Min.   : 0.0   Min.   :0.0   Min.   :0   Min.   : 74   Min.   :11  
##  1st Qu.: 5.0   1st Qu.:0.0   1st Qu.:0   1st Qu.: 93   1st Qu.:25  
##  Median : 7.0   Median :1.0   Median :0   Median :101   Median :29  
##  Mean   : 7.7   Mean   :1.4   Mean   :0   Mean   :101   Mean   :30  
##  3rd Qu.:10.0   3rd Qu.:2.0   3rd Qu.:0   3rd Qu.:108   3rd Qu.:34  
##  Max.   :18.0   Max.   :6.0   Max.   :0   Max.   :138   Max.   :50  
##     conseils      Medecins  
##  Min.   : 34   Min.   : 22  
##  1st Qu.: 63   1st Qu.: 45  
##  Median : 75   Median : 55  
##  Mean   : 87   Mean   : 93  
##  3rd Qu.:107   3rd Qu.:129  
##  Max.   :247   Max.   :386
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\NormalTok{d[d$date <}\StringTok{ "2013-04-24"} \NormalTok{|}\StringTok{ }\NormalTok{d$date >}\StringTok{  "2013-11-01"}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"date"}\NormalTok{,}\StringTok{"affaires"}\NormalTok{)]}
\KeywordTok{boxplot}\NormalTok{(x$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(x$date), }\DataTypeTok{main=}\StringTok{"Activité du SAMU 67"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{, }\DataTypeTok{sub=}\StringTok{"2013 = MOIS 1-4 et 11-12"}\NormalTok{, }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"yellow"}\NormalTok{,}\StringTok{"red"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/ac_67-1.pdf} \#\#\#\# chiffres
résumés sur l'année 2 014 pour la SAMU 67: - nombre d'affaires: 299 899
- moyenne des affaires/j: 822 - médiane des affaires/j: 784 - nombre
maximal d' affaires/j: 1 540 - nombre minimal d' affaires/j: 480

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  nombre d'intervention SMUR: 15 877
\item
  nombre moyen d'interventions SMUR: 44
\end{itemize}

\section{SAMU 68}\label{samu-68}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s68 <-}\StringTok{ }\NormalTok{d[d$service ==}\StringTok{ "SAMU 68"}\NormalTok{,]}
\CommentTok{# supprime les lignes dupliquées:}
\NormalTok{s68 <-}\StringTok{ }\NormalTok{s68[!}\KeywordTok{duplicated}\NormalTok{(s68$date),]}

\CommentTok{# nombre de jours renseignés}
\NormalTok{x <-}\StringTok{ }\KeywordTok{max}\NormalTok{(s68$date) -}\StringTok{ }\KeywordTok{min}\NormalTok{(s68$date)}
\KeywordTok{round}\NormalTok{(x *}\StringTok{ }\DecValTok{100} \NormalTok{/}\StringTok{ }\NormalTok{n, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time difference of 900 days
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xts_s68 <-}\StringTok{ }\KeywordTok{as.xts}\NormalTok{(s68, }\DataTypeTok{order.by =} \NormalTok{s68$date)}

\NormalTok{a <-}\StringTok{ }\KeywordTok{zoo}\NormalTok{(s68$affaires, s68$date)}
\KeywordTok{plot}\NormalTok{(a, }\DataTypeTok{col=}\StringTok{"palegreen"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"Activité du SAMU 68"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu68-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b <-}\StringTok{ }\KeywordTok{zoo}\NormalTok{(s68$conseils, s68$date)}
\KeywordTok{plot}\NormalTok{(b, }\DataTypeTok{col=}\StringTok{"palegreen"}\NormalTok{, }\DataTypeTok{main=}\StringTok{"Activité du SAMU 68"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre de conseils"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu68-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s68$affaires,}\KeywordTok{year}\NormalTok{(s68$date),sum)}
\CommentTok{# activité en nombre d'affaires}
\NormalTok{a}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   2006   2007   2008   2009   2010   2011   2012   2013   2014 
## 136443 140076 144826 154304 149929 122298  91300 192868 172720
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# myenne annuelle}
\NormalTok{moy68 <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(s68$affaires,}\KeywordTok{year}\NormalTok{(s68$date),mean)}
\NormalTok{moy68}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2006 2007 2008 2009 2010 2011 2012 2013 2014 
##  383  388  399  430  415  435  473  530  480
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(moy68, }\DataTypeTok{type=}\StringTok{"l"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nb.moyen d'affaires/j"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{""}\NormalTok{,}\DataTypeTok{main=}\StringTok{"SAMU 68 - Evolution du nombre des affaires"}\NormalTok{, }\DataTypeTok{axes =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{)}
\KeywordTok{axis}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{:}\DecValTok{9}\NormalTok{,}\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\DecValTok{2006}\NormalTok{:}\DecValTok{2014}\NormalTok{))}
\KeywordTok{axis}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu68-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# box plot. On détermine la journée la plus active en triant les enregistrements par nb affaires décroissant. ord[1] correspond à la ligne où le nb d'affaires est le plus élevé. Il s'agit de 2006, ce qui correspond à la colonne n°4. On marque la date en face du repère.}
\CommentTok{# De plus on ajoute la valeur moyenne sous forme de de rond rouges:}

\KeywordTok{boxplot}\NormalTok{(s68$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(s68$date), }\DataTypeTok{main=}\StringTok{"Activité du SAMU 68"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{)}
\NormalTok{for(i in }\DecValTok{1}\NormalTok{:}\DecValTok{9}\NormalTok{)\{}\KeywordTok{points}\NormalTok{(i,moy68[i],}\DataTypeTok{col=}\StringTok{"red"}\NormalTok{)\}}

\NormalTok{ord <-}\StringTok{ }\KeywordTok{order}\NormalTok{(s68$affaires,}\DataTypeTok{decreasing=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{s68[ord[}\DecValTok{1}\NormalTok{],]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            date service affaires primaires secondaires néonat TIIH ASSU
## 1813 2008-12-26 SAMU 68     1074        18           4      0    0    0
##      VSAV conseils Medecins
## 1813  107      556      474
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s68$date[ord[}\DecValTok{1}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2008-12-26"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{text}\NormalTok{(}\DecValTok{4}\NormalTok{, s68$affaires[ord[}\DecValTok{1}\NormalTok{]], s68$date[ord[}\DecValTok{1}\NormalTok{]],}\DataTypeTok{cex=}\NormalTok{.}\DecValTok{6}\NormalTok{,}\DataTypeTok{pos=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/samu68-4.pdf}

\subsection{Les 2 SAMU ensembles}\label{les-2-samu-ensembles}

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  \textbf{at} permet de décaler les boxplot pour qu'ils ne soient pas
  superposés
\item
  \textbf{boxwex} permet de diminuer la largeur d'un boxplot
\item
  \textbf{add} pour mettre les 2 graphiques sur le même dessin
\item
  \textbf{outline} = FALSE, ne dessine pas les observations extrèmes
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\NormalTok{d[d$date <}\StringTok{ "2013-04-24"} \NormalTok{|}\StringTok{ }\NormalTok{d$date >}\StringTok{  "2013-11-01"}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"date"}\NormalTok{,}\StringTok{"affaires"}\NormalTok{)]}
\NormalTok{n <-}\StringTok{ }\KeywordTok{unique}\NormalTok{(}\KeywordTok{year}\NormalTok{(x$date)) }\CommentTok{# nombre d'années}

\KeywordTok{boxplot}\NormalTok{(x$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(x$date), }\DataTypeTok{main=}\StringTok{"Activité du SAMU 67"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{, }\DataTypeTok{sub=}\StringTok{"2013 = MOIS 1-4 et 11-12"}\NormalTok{, }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"yellow"}\NormalTok{,}\StringTok{"red"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/deux_samu-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(x$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(x$date), }\DataTypeTok{main=}\StringTok{"Activité des SAMU d'Alsace"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Nombre d'affaires"}\NormalTok{, }\DataTypeTok{sub=}\StringTok{"MOIS 1-4 et 11-12"}\NormalTok{, }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"red"}\NormalTok{,}\StringTok{"yellow"}\NormalTok{,}\StringTok{"red"}\NormalTok{), }\DataTypeTok{at =} \DecValTok{1}\NormalTok{:}\DecValTok{9} \NormalTok{-}\StringTok{ }\FloatTok{0.3}\NormalTok{, }\DataTypeTok{boxwex=}\FloatTok{0.25}\NormalTok{, }\DataTypeTok{outline=}\OtherTok{FALSE}\NormalTok{)}

\CommentTok{# décommenter la ligne suivante:}
\KeywordTok{boxplot}\NormalTok{(s68$affaires ~}\StringTok{ }\KeywordTok{year}\NormalTok{(s68$date), }\DataTypeTok{col=}\StringTok{"green"}\NormalTok{, }\DataTypeTok{add=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{at =} \DecValTok{1}\NormalTok{:}\DecValTok{9}\FloatTok{+0.1}\NormalTok{, }\DataTypeTok{boxwex=}\FloatTok{0.25}\NormalTok{, }\DataTypeTok{names=}\KeywordTok{c}\NormalTok{(}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{,}\StringTok{""}\NormalTok{), }\DataTypeTok{outline=}\OtherTok{FALSE}\NormalTok{)}

\KeywordTok{legend}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1400}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"SAMU 67 "}\NormalTok{, }\StringTok{"SAMU 68"}\NormalTok{), }\DataTypeTok{fill =} \KeywordTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/deux_samu-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Boxplot de l'activité SMUR}
\CommentTok{#---------------------------}
\NormalTok{d$SMUR <-}\StringTok{ }\NormalTok{d$primaires +}\StringTok{ }\NormalTok{d$secondaires}
\NormalTok{moy_als <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(d$SMUR, }\KeywordTok{year}\NormalTok{(d$date), mean) }\CommentTok{# activité moyenne par}
\NormalTok{periode <-}\StringTok{ }\DecValTok{10}
\KeywordTok{boxplot}\NormalTok{(d$SMUR ~}\StringTok{ }\KeywordTok{year}\NormalTok{(d$date), }\DataTypeTok{main =} \StringTok{"Activité des SMUR Alsaciens"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Nombre d'SMUR"}\NormalTok{)}
\NormalTok{for (i in }\DecValTok{1}\NormalTok{:periode) \{ }\KeywordTok{points}\NormalTok{(i, moy_als[i], }\DataTypeTok{col =} \StringTok{"red"}\NormalTok{)\} }\CommentTok{# met act.moy sous forme de rond rouges}
\CommentTok{# on ajoute la date où le nb d'envoi de SMUR est le plus grand. Pour cela on trie les jours par ordre décroissant et les jours les plus actifs se trouvent en tête}
\NormalTok{ord <-}\StringTok{ }\KeywordTok{order}\NormalTok{(d$SMUR, }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{text}\NormalTok{(}\DecValTok{4}\NormalTok{, d$SMUR[ord[}\DecValTok{1}\NormalTok{]], d$date[ord[}\DecValTok{1}\NormalTok{]], }\DataTypeTok{cex =} \FloatTok{0.6}\NormalTok{, }\DataTypeTok{pos =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{samu_files/figure-latex/smur-1.pdf}

\subsection{Informations de session}\label{informations-de-session}

\begin{verbatim}
## R version 3.2.2 (2015-08-14)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 14.04.3 LTS
## 
## locale:
##  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
##  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
##  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] lubridate_1.3.3 xts_0.9-7       zoo_1.7-12      knitr_1.11     
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.2     lattice_0.20-33 digest_0.6.8    grid_3.2.2     
##  [5] plyr_1.8.3      formatR_1.2.1   magrittr_1.5    evaluate_0.8   
##  [9] stringi_1.0-1   rmarkdown_0.8.1 tools_3.2.2     stringr_1.0.0  
## [13] yaml_2.1.13     memoise_0.2.1   htmltools_0.2.6
\end{verbatim}

\end{document}
